
INSERT INTO Requirements (RequirementId, RequirementType, Inverse) VALUES
-- Difficulty levels
('REQUIRES_SETTLER', 'REQUIREMENT_PLAYER_HANDICAP_AT_OR_ABOVE', 0),
('REQUIRES_CHIEFTAIN', 'REQUIREMENT_PLAYER_HANDICAP_AT_OR_ABOVE', 0),
('REQUIRES_WARLORD', 'REQUIREMENT_PLAYER_HANDICAP_AT_OR_ABOVE', 0),
('REQUIRES_PRINCE', 'REQUIREMENT_PLAYER_HANDICAP_AT_OR_ABOVE', 0),
('REQUIRES_KING', 'REQUIREMENT_PLAYER_HANDICAP_AT_OR_ABOVE', 0),
('REQUIRES_EMPEROR', 'REQUIREMENT_PLAYER_HANDICAP_AT_OR_ABOVE', 0),
('REQUIRES_IMMORTAL', 'REQUIREMENT_PLAYER_HANDICAP_AT_OR_ABOVE', 0),
('REQUIRES_DEITY', 'REQUIREMENT_PLAYER_HANDICAP_AT_OR_ABOVE', 0),

-- Eras
('PLAYER_AT_CLASSICAL_ERA', 'REQUIREMENT_PLAYER_ERA_AT_LEAST', 0),
('PLAYER_AT_MEDIEVAL_ERA', 'REQUIREMENT_PLAYER_ERA_AT_LEAST', 0),
('PLAYER_AT_RENAISSANCE_ERA', 'REQUIREMENT_PLAYER_ERA_AT_LEAST', 0),
('PLAYER_AT_INDUSTRIAL_ERA', 'REQUIREMENT_PLAYER_ERA_AT_LEAST', 0),
('NOT_AT_INDUSTRIAL_ERA', 'REQUIREMENT_PLAYER_ERA_AT_LEAST', 1),
('PLAYER_AT_MODERN_ERA', 'REQUIREMENT_PLAYER_ERA_AT_LEAST', 0),
('PLAYER_AT_ATOMIC_ERA', 'REQUIREMENT_PLAYER_ERA_AT_LEAST', 0),
('NOT_AT_ATOMIC_ERA', 'REQUIREMENT_PLAYER_ERA_AT_LEAST', 1),
('PLAYER_AT_INFO_ERA', 'REQUIREMENT_PLAYER_ERA_AT_LEAST', 0);

INSERT INTO RequirementArguments (RequirementId, Name, Value) VALUES
-- Difficulty levels
('REQUIRES_SETTLER', 'Handicap', 'DIFFICULTY_SETTLER'),
('REQUIRES_CHIEFTAIN', 'Handicap', 'DIFFICULTY_CHIEFTAIN'),
('REQUIRES_WARLORD', 'Handicap', 'DIFFICULTY_WARLORD'),
('REQUIRES_PRINCE', 'Handicap', 'DIFFICULTY_PRINCE'),
('REQUIRES_KING', 'Handicap', 'DIFFICULTY_KING'),
('REQUIRES_EMPEROR', 'Handicap', 'DIFFICULTY_EMPEROR'),
('REQUIRES_IMMORTAL', 'Handicap', 'DIFFICULTY_IMMORTAL'),
('REQUIRES_DEITY', 'Handicap', 'DIFFICULTY_DEITY'),

-- Eras (unused for now, but figured I'd leave them here)
('PLAYER_AT_CLASSICAL_ERA', 'EraType', 'ERA_CLASSICAL'),
('PLAYER_AT_MEDIEVAL_ERA', 'EraType', 'ERA_MEDIEVAL'),
('PLAYER_AT_RENAISSANCE_ERA', 'EraType', 'ERA_RENAISSANCE'),
('PLAYER_AT_INDUSTRIAL_ERA', 'EraType', 'ERA_INDUSTRIAL'),
('NOT_AT_INDUSTRIAL_ERA', 'EraType', 'ERA_INDUSTRIAL'),
('PLAYER_AT_MODERN_ERA', 'EraType', 'ERA_MODERN'),
('PLAYER_AT_ATOMIC_ERA', 'EraType', 'ERA_ATOMIC'),
('NOT_AT_ATOMIC_ERA', 'EraType', 'ERA_ATOMIC'),
('PLAYER_AT_INFO_ERA', 'EraType', 'ERA_INFORMATION');